import { readFileSync, writeFileSync, renameSync, mkdirSync, readdirSync, existsSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import type { PermissionMode, PermissionUpdate } from "@anthropic-ai/claude-agent-sdk";
import type { ClientEvent } from "./session.js";

export type ChatRecord = {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;
  sdkSessionId: string | null;
  /** Absolute path this chat works in. Null means the server default. */
  cwd: string | null;
  /** True while the title is just the opening message, awaiting a real one. */
  titleProvisional?: boolean;
  /** Project id this chat belongs to; absent means the General project. */
  project?: string;
  events: ClientEvent[];
  granted: PermissionUpdate[];
  mode: PermissionMode;
};

/** Summary shown in the chat picker — never carries the whole transcript. */
export type ChatSummary =
  Pick<ChatRecord, "id" | "title" | "createdAt" | "updatedAt" | "cwd"> &
  { turns: number; project: string | null };

export class Store {
  #dir: string;

  constructor(dir: string) {
    this.#dir = dir;
    mkdirSync(dir, { recursive: true });
  }

  #path(id: string): string {
    // ids are generated by us (uuid), but never trust one off the wire.
    if (!/^[0-9a-f-]{36}$/i.test(id)) throw new Error("bad chat id");
    return join(this.#dir, `${id}.json`);
  }

  read(id: string): ChatRecord | null {
    const p = this.#path(id);
    if (!existsSync(p)) return null;
    try {
      const d = JSON.parse(readFileSync(p, "utf8")) as ChatRecord;
      return Array.isArray(d.events) ? d : null;
    } catch {
      return null;
    }
  }

  write(rec: ChatRecord): void {
    try {
      const p = this.#path(rec.id);
      writeFileSync(`${p}.tmp`, JSON.stringify(rec));
      renameSync(`${p}.tmp`, p);
    } catch { /* losing history is not worth crashing over */ }
  }

  remove(id: string): void {
    try { unlinkSync(this.#path(id)); } catch { /* already gone */ }
  }

  /** Newest first. Reads every file, which is fine at personal scale. */
  list(): ChatSummary[] {
    let names: string[];
    try { names = readdirSync(this.#dir).filter((n) => n.endsWith(".json")); } catch { return []; }

    const out: ChatSummary[] = [];
    for (const n of names) {
      try {
        const d = JSON.parse(readFileSync(join(this.#dir, n), "utf8")) as ChatRecord;
        if (!d?.id) continue;
        out.push({
          id: d.id,
          title: d.title || "(untitled)",
          createdAt: d.createdAt ?? 0,
          updatedAt: d.updatedAt ?? 0,
          cwd: d.cwd ?? null,
          project: d.project ?? null,
          turns: d.events.filter((e) => e.kind === "user").length,
        });
      } catch { /* skip a corrupt file rather than lose the list */ }
    }
    return out.sort((a, b) => b.updatedAt - a.updatedAt);
  }
}

/** First thing the user said, trimmed to something that fits a list. */
export function titleFrom(events: ClientEvent[]): string {
  const first = events.find((e) => e.kind === "user") as { text: string } | undefined;
  if (!first) return "New chat";
  const t = first.text.replace(/\s+/g, " ").trim();
  return t.length > 64 ? `${t.slice(0, 63)}…` : t;
}
