import { readFileSync, writeFileSync, renameSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { PermissionMode, PermissionUpdate } from "@anthropic-ai/claude-agent-sdk";
import type { ClientEvent } from "./session.js";

export type ChatRecord = {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;
  sdkSessionId: string | null;
  /** Absolute path this chat works in. Null means the server default. */
  cwd: string | null;
  /** True while the title is just the opening message, awaiting a real one. */
  titleProvisional?: boolean;
  /** Project id this chat belongs to; absent means the General project. */
  project?: string;
  events: ClientEvent[];
  granted: PermissionUpdate[];
  mode: PermissionMode;
};

/** Summary shown in the chat picker — never carries the whole transcript. */
export type ChatSummary =
  Pick<ChatRecord, "id" | "title" | "createdAt" | "updatedAt" | "cwd"> &
  { turns: number; project: string | null };

export class Store {
  #dir: string;
  /**
   * Summaries kept in memory so the chat picker does not re-read and re-parse
   * every ~60 KB record on each refresh — that was 62 ms synchronous for 500
   * chats, on the event loop, fired on every title change and every attach.
   * This Store is the only writer, so the cache stays authoritative; the boot
   * scan picks up whatever was written while the server was down.
   */
  #summaries = new Map<string, ChatSummary>();

  constructor(dir: string) {
    this.#dir = dir;
    mkdirSync(dir, { recursive: true });
    this.#scan();
  }

  get dir(): string { return this.#dir; }

  #summaryOf(d: ChatRecord): ChatSummary {
    return {
      id: d.id,
      title: d.title || "(untitled)",
      createdAt: d.createdAt ?? 0,
      updatedAt: d.updatedAt ?? 0,
      cwd: d.cwd ?? null,
      project: d.project ?? null,
      turns: d.events.filter((e) => e.kind === "user").length,
    };
  }

  /** One-time full read at construction; the cache carries it from there. */
  #scan(): void {
    let names: string[];
    try { names = readdirSync(this.#dir).filter((n) => n.endsWith(".json")); } catch { return; }
    for (const n of names) {
      try {
        const d = JSON.parse(readFileSync(join(this.#dir, n), "utf8")) as ChatRecord;
        if (d?.id && Array.isArray(d.events)) this.#summaries.set(d.id, this.#summaryOf(d));
      } catch { /* skip a corrupt file rather than lose the list */ }
    }
  }

  /** Sibling of the chats dir, so a delete is recoverable with one `mv`. */
  get #archiveDir(): string { return `${this.#dir}-archive`; }

  #path(id: string): string {
    // ids are generated by us (uuid), but never trust one off the wire.
    if (!/^[0-9a-f-]{36}$/i.test(id)) throw new Error("bad chat id");
    return join(this.#dir, `${id}.json`);
  }

  read(id: string): ChatRecord | null {
    const p = this.#path(id);
    if (!existsSync(p)) return null;
    try {
      const d = JSON.parse(readFileSync(p, "utf8")) as ChatRecord;
      return Array.isArray(d.events) ? d : null;
    } catch {
      return null;
    }
  }

  write(rec: ChatRecord): void {
    try {
      const p = this.#path(rec.id);
      writeFileSync(`${p}.tmp`, JSON.stringify(rec));
      renameSync(`${p}.tmp`, p);
      this.#summaries.set(rec.id, this.#summaryOf(rec));   // keep the cache in step
    } catch { /* losing history is not worth crashing over */ }
  }

  /**
   * Deleting a chat used to unlinkSync it: silent, unlogged, unrecoverable.
   * Two chats vanished that way with nothing in the journal to explain it.
   * Now a delete is a move into chats-archive/ plus a log line, so a stray
   * click or a stray ws message costs a `mv` to undo rather than the data.
   */
  remove(id: string): void {
    const from = this.#path(id);
    if (!existsSync(from)) return;
    const dest = join(this.#archiveDir, `${id}-deleted-${Date.now()}.json`);
    try {
      mkdirSync(this.#archiveDir, { recursive: true });
      renameSync(from, dest);
      this.#summaries.delete(id);   // only once the file is actually gone
      console.log(`[chats] deleted ${id} -> ${dest}`);
    } catch (e) {
      // Never crash on a failed delete, but never fail silently either.
      console.error(`[chats] could not archive ${id}:`, e);
    }
  }

  /** Newest first, served from the in-memory cache — no disk read per call. */
  list(): ChatSummary[] {
    return [...this.#summaries.values()].sort((a, b) => b.updatedAt - a.updatedAt);
  }
}

/** First thing the user said, trimmed to something that fits a list. */
export function titleFrom(events: ClientEvent[]): string {
  const first = events.find((e) => e.kind === "user") as { text: string } | undefined;
  if (!first) return "New chat";
  const t = first.text.replace(/\s+/g, " ").trim();
  return t.length > 64 ? `${t.slice(0, 63)}…` : t;
}
